name: signinator
description: This is base for my project in flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use as default SVG image loader, prefer use SVG as image asset
  flutter_svg: ^2.0.0+1

  # Functional programming thingies
  dartz: ^0.10.1

  # Use as Network Client
  dio: ^4.0.6

  # Use as sharedPreferences to save local data
  shared_preferences: ^2.0.17

  # Use for Dependencies Injection
  get_it: ^7.2.0

  # State Management
  flutter_bloc: ^8.1.2
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  # Use for Time/Date Format
  intl: any

  # Draw waves and other custom clip background shapes 
  svg_path_parser: ^1.1.1

  # Use for responsive UI, set default size base on Mock Up
  # flutter_screenutil: ^5.6.1

  # logger
  logger: ^1.1.0

  # router
  go_router: ^6.5.7

  # provide values inside elements tree
  provider: ^6.0.5

  # Freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  http_mock_adapter: ^0.3.3

  # Temporary using old version because error when generate build_runner
  mockito: ^5.3.2

  # State management
  mobx_codegen: ^2.2.0

  # Freezed
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
